apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: teste
  name: teste
spec:
  replicas: 5
  selector:
    matchLabels:
      app: teste
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teste
    spec:
      volumes:
      - name: secret-vol
        secret:
          secretName: basic-auth
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          # name must match the volume name below
          - name: secret-vol
            mountPath: /etc/secret
            readOnly: true
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
status: {}
