apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  containers:
  - image: nginx:1.21.6
    name: nginx
    resources: {}
    volumeMounts:
    - mountPath: /var/log/nginx
      name: cache-volume
  - args:
    - /bin/sh
    - -c
    - tail -n+1 -f /var/log/nginx/access.log
    image: busybox:1.35.0
    name: streaming
    resources: {}
    volumeMounts:
    - mountPath: /var/log/nginx
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
