apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress-2
  name: stress-2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - stress --vm 1 --vm-bytes $(shuf -i 20-200 -n 1)M --vm-hang 1
    image: polinux/stress:1.0.4
    name: stress-2
    resources: 
      requests:
        memory: 250Mi
      limits:
        memory: 250Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
