apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1312-pv
  namespace: ckad-1312
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  hostPath:
    path: /tmp
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /tmp
#    server: 172.17.0.2
