apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  hostPath:
    path: "/tmp/logs"
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
