apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynewweb
    type: canary
  name: mynewweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynewweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynewweb
        type: canary
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
