apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: current-date
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: current-date
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Current date: $(date)"'
            image: nginx:1.25.1
            name: current-date
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
