apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: random-hash
spec:
  completions: 5
  parallelism: 2

  template:

    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo $RANDOM | base64 | head -c 20
        image: alpine
        name: random-hash
        resources: {}
      restartPolicy: Never
status: {}
