apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
  namespace: ckad-ns3
  labels:
    app: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', 'while true; do date >> /var/log/date.log; sleep 5; done']
          volumeMounts:
            - name: data
              mountPath: /var/log
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          hostPath: 
            path: /mydata
