apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste
  name: teste
  namespace: ckad-ns3
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do date >> /var/date.log; sleep 5; done
    image: busybox
    name: teste
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
