apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: hazelcast
    env: prod
  name: hazelcast
spec:
  containers:
  - env:
    - name: DNS_DOMAIN
      value: cluster
    - name: TESTE_GUSTAVO
      value: moraes
    image: hazelcast/hazelcast:5.1.7
    name: hazelcast
    ports:
    - containerPort: 5701
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
