apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: disposable
  name: disposable
  namespace: rm
spec:
  containers:
  - image: nginx
    name: disposable
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
