apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmpod
  name: tmpod
spec:
  serviceAccountName: testsa
  containers:
  - image: nginx:alpine
    name: tmpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
